name: youthshare

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0-23/3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Lovezbfu/sn0415.git ~/sn0415
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/sn0415
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【youthshare】'
        run: |
          cd ~/sn0415   
          node Task/youthshare.js
